{"name": "test01_success", "status": "failed", "statusDetails": {"message": "AssertionError: assert '成功' in '{\"msg\":\"用户不存在/密码错误\",\"code\":500}'\n +  where '{\"msg\":\"用户不存在/密码错误\",\"code\":500}' = <Response [200]>.text", "trace": "self = <script.test04_login.TestLoginAPI object at 0x000002A34F9661C0>\n\n    def test01_success(self):\n        login_data = {\n            \"username\": \"manager\",\n            \"password\": \"123456\",\n            \"code\": \"2\",\n            \"uuid\": TestLoginAPI.uuid\n        }\n        response = self.login_api.login(test_data=login_data)\n        # 断言响应状态码为200\n        assert 200 == response.status_code\n        # 断言响应数据包含'成功'\n>       assert '成功' in response.text\nE       assert '成功' in '{\"msg\":\"用户不存在/密码错误\",\"code\":500}'\nE        +  where '{\"msg\":\"用户不存在/密码错误\",\"code\":500}' = <Response [200]>.text\n\ntest04_login.py:37: AssertionError"}, "start": 1754968685979, "stop": 1754968686268, "uuid": "de47f04a-5ea2-4f48-80f9-1e36aafe97c0", "historyId": "a22aabc11a3519f6d551a0d3731aa154", "testCaseId": "a22aabc11a3519f6d551a0d3731aa154", "fullName": "script.test04_login.TestLoginAPI#test01_success", "labels": [{"name": "parentSuite", "value": "script"}, {"name": "suite", "value": "test04_login"}, {"name": "subSuite", "value": "TestLoginAPI"}, {"name": "host", "value": "渐入佳境"}, {"name": "thread", "value": "1212-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "script.test04_login"}]}